#!/usr/bin/env python3
"""
CEO Baseline Creator

Runs ONCE at project inception to lock the original investment thesis.
This file is the source of truth for all future alignment checks.

Called by new_project_generator.py or manually:
  echo '{"project_id": "...", "irr_target": 14.5, ...}' | python3 create_ceo_baseline.py
"""

import sys
import json
from datetime import datetime
from pathlib import Path

SDARPP_OPS_ROOT = Path(__file__).parent.parent.parent
PROJECTS_DIR    = SDARPP_OPS_ROOT / "projects"


def create_baseline(project_id: str, data: dict) -> Path:
    """Create and lock the CEO baseline JSON file"""

    baseline = {
        # ── Identity ─────────────────────────────────────────
        "project_id":           project_id,
        "project_name":         data.get("project_name", project_id),
        "address":              data.get("address", "TBD"),
        "state":                data.get("state", "VIC"),
        "lga":                  data.get("lga", "TBD"),
        "baseline_locked":      datetime.now().isoformat(),
        "locked_by":            "new_project_generator / Project Director",

        # ── Financial targets (LOCKED) ────────────────────────
        "irr_target_pct":            data.get("irr_target", 14.5),
        "irr_amber_threshold":       data.get("irr_amber", 13.0),
        "irr_red_threshold":         data.get("irr_red", 12.0),
        "irr_terminate_threshold":   data.get("irr_terminate", 11.0),

        "dscr_target":               data.get("dscr_target", 1.27),
        "dscr_amber_threshold":      data.get("dscr_amber", 1.20),
        "dscr_red_threshold":        data.get("dscr_red", 1.15),
        "dscr_terminate_threshold":  data.get("dscr_terminate", 1.10),

        "dev_margin_target_pct":     data.get("dev_margin_target", 17.5),
        "dev_margin_amber":          data.get("dev_margin_amber", 13.0),
        "dev_margin_red":            data.get("dev_margin_red", 10.0),
        "dev_margin_terminate":      data.get("dev_margin_terminate", 8.0),

        # ── Capital structure ─────────────────────────────────
        "tdc_estimate_aud":          data.get("tdc_estimate", 0),
        "tdc_amber_pct":             15,    # +15% of original = AMBER
        "tdc_red_pct":               25,    # +25% = RED
        "tdc_terminate_pct":         35,    # +35% = TERMINATE

        # ── Revenue model ──────────────────────────────────────
        "revenue_streams_target":    data.get("revenue_streams", 4),
        "revenue_streams_amber":     3,
        "revenue_streams_red":       2,
        "revenue_streams_terminate": 1,

        "sda_pct_max":               40,    # SDA must stay ≤40% of revenue — AMBER
        "sda_pct_red":               50,
        "sda_pct_terminate":         65,

        "annual_revenue_target_aud": data.get("annual_revenue_target", 0),

        # ── Mixed-use model ────────────────────────────────────
        "mixed_use_required":        True,
        "clinical_anchor_required":  True,   # CSSD or medical hub must be present
        "min_revenue_streams":       4,

        # ── Timeline ───────────────────────────────────────────
        "stage_1_target_date":       data.get("stage_1_date", ""),
        "stage_2_target_date":       data.get("stage_2_date", ""),
        "stage_3_target_date":       data.get("stage_3_date", ""),
        "da_lodgement_target":       data.get("da_lodgement_date", ""),
        "construction_start_target": data.get("construction_start_date", ""),
        "completion_target":         data.get("completion_date", ""),
        "timeline_amber_months":     3,
        "timeline_red_months":       6,
        "timeline_terminate_months": 12,

        # ── Design model ───────────────────────────────────────
        "gfa_target_sqm":            data.get("gfa_target", 0),
        "sda_units_target":          data.get("sda_units", 4),
        "vmo_suites_target":         data.get("vmo_suites", 16),
        "cssd_required":             data.get("cssd_required", True),
        "medical_hub_required":      data.get("medical_hub_required", True),

        # ── Reference model (Day Street Wodonga) ──────────────
        "reference_project":         "VIC-SDA-WODONGA-2025",
        "reference_model":           "Mixed-Use Healthcare Hub",

        # ── Notes ──────────────────────────────────────────────
        "notes": data.get("notes", ""),

        # ── LOCK NOTICE ────────────────────────────────────────
        "_LOCK_NOTICE": (
            "This file is LOCKED at project inception. "
            "Any changes require documented Board decision. "
            "The CEO Alignment Monitor compares ALL future project updates against these values. "
            "Do NOT edit this file without formal governance approval."
        )
    }

    # Save baseline
    project_dir  = PROJECTS_DIR / project_id
    project_dir.mkdir(parents=True, exist_ok=True)
    baseline_path = project_dir / "ceo-baseline.json"

    with open(baseline_path, "w", encoding="utf-8") as f:
        json.dump(baseline, f, indent=2, ensure_ascii=False)

    print(f"✅ CEO Baseline LOCKED: {baseline_path}")

    # Also write a human-readable markdown summary
    md_content = f"""# CEO Baseline — {project_id}

> **⚠️ THIS FILE IS LOCKED AT PROJECT INCEPTION**
> Any changes require a formal Board decision.
> The CEO Alignment Monitor uses this file to detect project drift.

**Locked:** {datetime.now().strftime('%d/%m/%Y %H:%M AEST')}
**Project:** {baseline['project_name']}
**Address:** {baseline['address']}

---

## Financial Targets (LOCKED)

| Metric | Target | Amber Alert | Red Alert | Terminate |
|--------|--------|-------------|-----------|-----------|
| IRR | ≥{baseline['irr_target_pct']}% | <{baseline['irr_amber_threshold']}% | <{baseline['irr_red_threshold']}% | <{baseline['irr_terminate_threshold']}% |
| DSCR | ≥{baseline['dscr_target']}x | <{baseline['dscr_amber_threshold']}x | <{baseline['dscr_red_threshold']}x | <{baseline['dscr_terminate_threshold']}x |
| Dev Margin | ≥{baseline['dev_margin_target_pct']}% | <{baseline['dev_margin_amber']}% | <{baseline['dev_margin_red']}% | <{baseline['dev_margin_terminate']}% |
| TDC | ${baseline['tdc_estimate_aud']:,} | +{baseline['tdc_amber_pct']}% | +{baseline['tdc_red_pct']}% | +{baseline['tdc_terminate_pct']}% |
| Revenue Streams | {baseline['revenue_streams_target']} | {baseline['revenue_streams_amber']} | {baseline['revenue_streams_red']} | {baseline['revenue_streams_terminate']} |
| SDA % Max | {baseline['sda_pct_max']}% | {baseline['sda_pct_max']}% | {baseline['sda_pct_red']}% | {baseline['sda_pct_terminate']}% |

## Design Targets (LOCKED)

| Element | Target |
|---------|--------|
| GFA | {baseline['gfa_target_sqm']:,} sqm |
| SDA Units | {baseline['sda_units_target']} × HPS |
| VMO Suites | {baseline['vmo_suites_target']} |
| CSSD Required | {'Yes' if baseline['cssd_required'] else 'No'} |
| Medical Hub Required | {'Yes' if baseline['medical_hub_required'] else 'No'} |
| Mixed-Use Model | {'MANDATORY' if baseline['mixed_use_required'] else 'Optional'} |

## Timeline Targets (LOCKED)

| Stage | Target Date |
|-------|------------|
| Stage 1 | {baseline['stage_1_target_date'] or 'TBD'} |
| Stage 2 | {baseline['stage_2_target_date'] or 'TBD'} |
| DA Lodgement | {baseline['da_lodgement_target'] or 'TBD'} |
| Construction Start | {baseline['construction_start_target'] or 'TBD'} |
| Completion | {baseline['completion_target'] or 'TBD'} |

---

*CEO Alignment Monitor will alert Project Director if any metric drifts beyond thresholds above.*
"""

    md_path = project_dir / "ceo-baseline.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"✅ CEO Baseline summary: {md_path}")
    return baseline_path


def main():
    stdin_data = sys.stdin.read().strip()
    if stdin_data:
        data = json.loads(stdin_data)
    else:
        print("ERROR: No data on stdin")
        sys.exit(1)

    project_id = data.get("project_id")
    if not project_id:
        print("ERROR: project_id required")
        sys.exit(1)

    path = create_baseline(project_id, data)
    print(json.dumps({"status": "created", "baseline_path": str(path)}, indent=2))


if __name__ == "__main__":
    main()
