#!/bin/bash

# SDARPP Weekly Governance Summary Generator
#
# Aggregates governance changes across all projects for the past 7 days
# and generates a weekly summary report.
#
# Runs Monday morning (07:00 AEDT) via GitHub Actions
# Outputs: projects/[id]/governance/weekly-summary-YYYY-MM-DD.md

set -e

# Configuration
ONEDRIVE_BASE="$HOME/Library/CloudStorage/OneDrive-SDArpp/05. SDARPP Operations"
GIT_REPO="."
DAYS_BACK=7

# Get week start date
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    WEEK_START=$(date -u -v-6d +%Y-%m-%d)
else
    # Linux
    WEEK_START=$(date -u -d "6 days ago" +%Y-%m-%d)
fi
TODAY=$(date +%Y-%m-%d)

echo "📋 SDARPP Weekly Governance Summary Generator"
echo "════════════════════════════════════════════"
echo "Period: $WEEK_START to $TODAY"
echo "Working directory: $PWD"
echo ""

# Function to scan project for changes
scan_project_changes() {
    local project_path="$1"
    local project_id=$(basename "$project_path")

    echo "  Scanning: $project_id"

    # Check for decision log updates
    if [ -f "$project_path/governance/decision-log.md" ]; then
        local decision_count=$(grep -c "^## " "$project_path/governance/decision-log.md" 2>/dev/null || echo 0)
        if [ $decision_count -gt 0 ]; then
            echo "    ✅ Decision log entries: $decision_count"
        fi
    fi

    # Check for risk register updates
    if [ -f "$project_path/governance/risk-register.md" ]; then
        local risk_count=$(grep -c "^### " "$project_path/governance/risk-register.md" 2>/dev/null || echo 0)
        if [ $risk_count -gt 0 ]; then
            echo "    ✅ Active risks: $risk_count"
        fi
    fi

    # Check for status report updates
    if [ -f "$project_path/governance/project-status.md" ]; then
        echo "    ✅ Status report available"
    fi
}

# Main
PROJECTS_SCANNED=0
SUMMARIES_GENERATED=0

# Scan all state folders
for state_folder in "$ONEDRIVE_BASE/0"*"Projects"*"/"; do
    if [ ! -d "$state_folder" ]; then
        continue
    fi

    STATE=$(basename "$state_folder")
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "📍 $STATE"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    # Scan projects in this state
    for project_path in "$state_folder"/*/; do
        project_name=$(basename "$project_path")

        # Skip state admin folder
        if [[ "$project_name" == _STATE-ADMIN* ]]; then
            continue
        fi

        if [ -d "$project_path/governance" ]; then
            ((PROJECTS_SCANNED++))
            scan_project_changes "$project_path"

            # Generate summary (placeholder - in production, this would aggregate data)
            SUMMARY_FILE="$project_path/governance/weekly-summary-$TODAY.md"

            # Create summary markdown
            cat >"$SUMMARY_FILE" <<EOF
# Weekly Governance Summary — $project_name

**Week of:** $WEEK_START to $TODAY
**Generated:** $TODAY at $(date +%H:%M:%S UTC)

## Executive Summary

This week's governance summary for **$project_name** covering risk, decisions, and status updates.

_Data aggregation in progress - this is a template structure._

### Key Metrics
- Active risks: TBD
- Decisions made: TBD
- Compliance issues: TBD
- Milestones on track: TBD

## Decision Log

See: \`governance/decision-log.md\`

## Risk Register

See: \`governance/risk-register.md\`

## Action Items

| Item | Owner | Due Date | Status |
|------|-------|----------|--------|
| TBD | TBD | TBD | ⏳ Pending |

---

**Generated by:** SDARPP Weekly Summary Automation
**Review Status:** ⏳ PENDING HUMAN REVIEW

This summary requires human review and approval before being committed to main.
EOF

            ((SUMMARIES_GENERATED++))
            echo "    📝 Summary generated: $SUMMARY_FILE"
        fi
    done
done

# Summary
echo ""
echo "════════════════════════════════════════════"
echo "✅ Summary Generation Complete"
echo "════════════════════════════════════════════"
echo "Projects scanned: $PROJECTS_SCANNED"
echo "Summaries generated: $SUMMARIES_GENERATED"
echo ""
echo "Next step: Review generated summaries and commit to GitHub"
echo "Location: projects/[id]/governance/weekly-summary-$TODAY.md"
