#!/usr/bin/env python3
"""
SDARPP New Project Generator

Creates a complete new project structure:
  - sdarpp-operations/projects/[PROJECT-ID]/
  - Full wiki (state, decisions, risks, schedule, budget, stakeholders)
  - Agent contracts
  - GitHub Actions workflows
  - All automation scripts

Usage:
  python3 new_project_generator.py --project-id VIC-HUB-SUBURB-2026 \
      --name "Suburb, State Development" \
      --address "123 Street, Suburb VIC 0000" \
      --state VIC \
      --lga "Council Name" \
      --land-area "2,500 sqm" \
      --zoning "Commercial Zone 1" \
      --proposed-use "Mixed-Use Healthcare Hub"
"""

import os
import sys
import argparse
import json
import subprocess
from datetime import datetime
from pathlib import Path

# ── Repo roots ──────────────────────────────────────────────
SDARPP_OPS_ROOT = Path(__file__).parent.parent.parent   # sdarpp-operations/
TEMPLATE_DIR    = SDARPP_OPS_ROOT / "templates" / "project-setup"


# ── Helper ───────────────────────────────────────────────────
def render(template_text: str, ctx: dict) -> str:
    """Simple {{KEY}} substitution"""
    for k, v in ctx.items():
        template_text = template_text.replace("{{" + k + "}}", str(v))
    return template_text


def write_file(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  ✅ {path.relative_to(SDARPP_OPS_ROOT.parent)}")


# ── Template content functions ────────────────────────────────
def readme(ctx):
    return render("""# {{PROJECT_NAME}} — SDARPP Development Project

**Project ID:** {{PROJECT_ID}}
**Location:** {{ADDRESS}}
**State:** {{STATE}}
**LGA:** {{LGA}}
**Repository:** [project-{{PROJECT_ID_LOWER}}](https://github.com/sdarpp-development-os/project-{{PROJECT_ID_LOWER}})
**Created:** {{DATE}}

---

## Project Status

| Attribute | Value |
|-----------|-------|
| **Stage** | Stage 1 (Site Analysis & Intelligence) |
| **Stage Start** | {{DATE}} |
| **Current Focus** | DIBA Site Analysis + Design PoC |
| **Project Director** | Sugi Gunamijaya |

---

## Development Model

**Mixed-Use Healthcare Hub** (SDARPP design philosophy)

- CSSD / Clinical Institutional Services
- Medical / Allied Health Hub
- Clinical Transition / Step-Down Care
- NDIS SDA (High Physical Support)
- VMO / Private Accommodation

---

## Agent Team

| Agent | Role | Trigger |
|-------|------|---------|
| DIBA | Development Intelligence Briefing | New project created |
| Site Investigator | Planning rules + constraints | After DIBA |
| Design PoC | 4-scenario concept design | After Site Investigator |
| HBU Analyst | Highest & Best Use analysis | After Design PoC |
| Income Maximiser | Revenue optimisation | After HBU |
| Risk Escalator | Ongoing risk monitoring | Continuous |
| Compliance | Governance audit | Weekly |

---

## Key Links

- [Project State](wiki/project_state.md)
- [Decisions Register](wiki/decisions.md)
- [Risk Register](wiki/risks.md)
- [Budget](wiki/budget.md)
- [Schedule](wiki/schedule.md)
- [DIBA Briefing](wiki/) ← Generated by agent
""", ctx)


def project_state(ctx):
    return render("""# Project State — {{PROJECT_NAME}}

**Last Updated:** {{DATE}}
**Stage:** 1 — Site Analysis & Intelligence
**Status:** 🔵 Active

---

## Site Details

| Field | Value |
|-------|-------|
| Project ID | {{PROJECT_ID}} |
| Address | {{ADDRESS}} |
| State | {{STATE}} |
| LGA | {{LGA}} |
| Land Area | {{LAND_AREA}} |
| Current Zoning | {{ZONING}} |
| Proposed Use | {{PROPOSED_USE}} |

---

## Stage Progress

- [ ] Stage 1A — DIBA Site Intelligence Briefing
- [ ] Stage 1B — Site Investigation (planning constraints)
- [ ] Stage 1C — Design PoC (4 scenarios)
- [ ] Stage 1D — HBU + Income Analysis
- [ ] Stage 2 — Design Development
- [ ] Stage 3 — DA Preparation
- [ ] Stage 4 — Construction
- [ ] Stage 5 — Operations

---

## Current Blockers

None identified.

---

## Agent Run Log

| Date | Agent | Output |
|------|-------|--------|
| {{DATE}} | New Project Generator | Project structure created |

""", ctx)


def decisions_register(ctx):
    return render("""# Decision Register — {{PROJECT_NAME}}

| # | Decision | Owner | Date | Status | Rationale |
|---|----------|-------|------|--------|-----------|
| 1 | Proceed with SDARPP Mixed-Use Healthcare Hub model | Project Director | {{DATE}} | Approved | Aligns with SDARPP philosophy — 4+ revenue streams required |
| 2 | Commence DIBA site analysis before any design work | Project Director | {{DATE}} | Approved | Intelligence-first approach — no design without planning clarity |
| 3 | Commission 4-scenario Design PoC | Project Director | {{DATE}} | Pending | AS IS / Potential / Max Value / Special Use to determine best path |

---

*All major decisions require Project Director sign-off before implementation.*
""", ctx)


def risk_register(ctx):
    return render("""# Risk Register — {{PROJECT_NAME}}

| # | Risk | Category | RAG | Probability | Impact | Owner | Mitigation |
|---|------|----------|-----|-------------|--------|-------|------------|
| R01 | Planning refusal or excessive conditions | Planning | 🟡 Amber | Medium | High | Project Director | DIBA + site investigation to clarify pathway before any DA lodgement |
| R02 | NDIS SDA policy change reducing revenue | Regulatory | 🟡 Amber | Low | High | Project Director | Mixed-use model reduces SDA dependency below 40% of total revenue |
| R03 | Construction cost escalation | Financial | 🟡 Amber | Medium | High | Project Director | Use P50/P90 cost model; early contractor engagement |
| R04 | Site contamination or infrastructure constraints | Site | 🔴 Red | Unknown | High | Project Director | Commission Phase 1 Environmental + infrastructure servicing report |
| R05 | Insufficient NDIS SDA demand in catchment | Market | 🟡 Amber | Low | Medium | Project Director | DIBA to validate local demand data; SDA not primary revenue driver |

---

*Updated automatically by Risk Escalator agent on each execution cycle.*
""", ctx)


def budget_template(ctx):
    return render("""# Budget Summary — {{PROJECT_NAME}}

**Status:** Pre-Feasibility (Indicative Only)
**Last Updated:** {{DATE}}

---

## Development Cost Estimate (Indicative)

| Cost Item | Indicative Range | Notes |
|-----------|-----------------|-------|
| Land Acquisition | TBD | Pending due diligence |
| Construction (Hard Costs) | TBD | Pending Design PoC |
| Professional Fees | ~10-12% of hard costs | Planning, design, project management |
| Finance Costs | ~6-8% p.a. | Pending capital stack confirmation |
| Contingency | 15% hard costs | Regional project allowance |
| **Total Development Cost** | **TBD** | To be refined post-DIBA |

---

## Capital Stack (Target)

| Source | Type | % of TDC | Notes |
|--------|------|----------|-------|
| State / Federal Grants | Non-repayable | 20-40% | Subject to DIBA grant mapping |
| Senior Debt | Loan | 40-50% | Subject to DSCR 1.25x+ |
| Equity / Impact Capital | Equity | 15-25% | SPV structure |
| **Total** | | **100%** | |

---

## Financial Targets

| Metric | Target |
|--------|--------|
| IRR | 14-16% |
| DSCR | 1.25-1.30x |
| Development Margin | 15-20% |
| Payback Period | 7-10 years |

---

*Full financial model to be completed in Stage 2 following DIBA and Design PoC.*
""", ctx)


def schedule_template(ctx):
    return render("""# Project Schedule — {{PROJECT_NAME}}

**Created:** {{DATE}}
**Status:** Stage 1 — Site Analysis

---

## Stage 1: Site Analysis & Intelligence (Current)

| Milestone | Target | Status |
|-----------|--------|--------|
| 1.1 DIBA Site Briefing | Week 1 | 🔵 In Progress |
| 1.2 Site Investigation Report | Week 2 | ⏳ Pending |
| 1.3 Design PoC (4 scenarios) | Week 3-4 | ⏳ Pending |
| 1.4 HBU + Income Analysis | Week 4 | ⏳ Pending |
| 1.5 Stage 1 Board Review | Week 5 | ⏳ Pending |

## Stage 2: Design Development

| Milestone | Target | Status |
|-----------|--------|--------|
| 2.1 Preferred scenario selection | TBD | ⏳ Pending |
| 2.2 Concept design (RAIA architect) | TBD | ⏳ Pending |
| 2.3 Cost plan (quantity surveyor) | TBD | ⏳ Pending |
| 2.4 Planning pre-application meeting | TBD | ⏳ Pending |

## Stage 3: DA Preparation

TBD — pending Stage 2 outcomes.

## Stage 4-5: Construction & Operations

TBD — pending DA approval.
""", ctx)


def stakeholder_list(ctx):
    return render("""# Stakeholder Register — {{PROJECT_NAME}}

| # | Stakeholder | Organisation | Role | Contact | Engagement Level |
|---|-------------|-------------|------|---------|-----------------|
| 1 | Sugi Gunamijaya | SDARPP | Project Director | — | Lead |
| 2 | TBD | {{LGA}} | Planning Officer | — | High |
| 3 | TBD | NDIS Commission | SDA Advisor | — | Medium |
| 4 | TBD | State Health Dept ({{STATE}}) | Health Infrastructure | — | Medium |
| 5 | TBD | Local Aboriginal Land Council | First Nations | — | High |
| 6 | TBD | Institutional Investor | Impact Capital | — | High |
| 7 | TBD | Healthcare Operator | Headlease Partner | — | High |

---

*First Nations engagement must be initiated in Stage 1 prior to any design work.*
""", ctx)


def wiki_index(ctx):
    return render("""# {{PROJECT_NAME}} — Project Wiki

**Project ID:** {{PROJECT_ID}}
**Stage:** 1 — Site Analysis & Intelligence

## Documents

| Document | Purpose | Last Updated |
|----------|---------|-------------|
| [Project State](project_state.md) | Current status and progress | {{DATE}} |
| [Decisions Register](decisions.md) | All project decisions | {{DATE}} |
| [Risk Register](risks.md) | Risk tracking and RAG status | {{DATE}} |
| [Budget](budget.md) | Cost estimates and capital stack | {{DATE}} |
| [Schedule](schedule.md) | Milestone timeline | {{DATE}} |
| [Stakeholders](stakeholder_list.md) | Key parties and contacts | {{DATE}} |
| DIBA Briefing | Development Intelligence (AI generated) | Pending |
| Site Investigation | Planning constraints analysis | Pending |
| Design PoC | 4-scenario concept report | Pending |

---

*All documents updated by agent team automatically.*
""", ctx)


def agent_job_site_investigation(ctx):
    """Pre-filled GitHub Issue body to trigger Site Investigation after DIBA"""
    return render("""\
## Agent Target
- [x] Site Investigator

## Job Payload
```json
{
  "jobType": "site_investigation",
  "priority": "high",
  "data": {
    "project_id": "{{PROJECT_ID}}",
    "address": "{{ADDRESS}}",
    "state": "{{STATE}}",
    "lga": "{{LGA}}",
    "zoning": "{{ZONING}}",
    "proposed_use": "{{PROPOSED_USE}}"
  }
}
```

## Required By
ASAP — triggers Design PoC after completion.
""", ctx)


def diba_issue_body(ctx):
    return render("""\
## New Project: Development Intelligence Briefing

```json
{
  "project_id": "{{PROJECT_ID_LOWER}}",
  "project_name": "{{PROJECT_NAME}}",
  "site_address": "{{ADDRESS}}",
  "state": "{{STATE}}",
  "lga": "{{LGA}}",
  "land_area": "{{LAND_AREA}}",
  "current_use": "{{CURRENT_USE}}",
  "zoning": "{{ZONING}}",
  "proposed_use": "{{PROPOSED_USE}}",
  "site_description": "New SDARPP project site. Mixed-Use Healthcare Hub model target.",
  "additional_context": "SDARPP philosophy: 4+ revenue streams. Target DSCR 1.25-1.30x, IRR 14-16%. Apply smart cache — reuse ESG and First Nations state-level data if <12 months old. Fetch site-specific LGA planning rules and local Aboriginal land council. Run 4-scenario Design PoC after briefing."
}
```

## Sections Required

- [x] 1. Planning & Zoning Uplift
- [x] 2. Infrastructure & Contributions
- [x] 3. Demand & Policy Need
- [x] 4. Capital Stack & Income
- [x] 5. Delivery & Partnership Models
- [x] 6. ESG, First Nations & Social Value
- [x] 7. Replicability & Scalability
- [x] 8. GO / CONDITIONAL / NO-GO Recommendation
""", ctx)


# ── Main ──────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="SDARPP New Project Generator")
    parser.add_argument("--project-id",    required=True,  help="e.g. VIC-HUB-SUBURB-2026")
    parser.add_argument("--name",          required=True,  help="e.g. 'Suburb, State Development'")
    parser.add_argument("--address",       required=True)
    parser.add_argument("--state",         required=True,  choices=["VIC","NSW","WA","SA","QLD","TAS","NT","ACT"])
    parser.add_argument("--lga",           required=True)
    parser.add_argument("--land-area",     default="TBD")
    parser.add_argument("--current-use",   default="TBD")
    parser.add_argument("--zoning",        default="TBD")
    parser.add_argument("--proposed-use",  default="Mixed-Use Healthcare Hub")
    args = parser.parse_args()

    date_str = datetime.now().strftime("%d/%m/%Y")

    ctx = {
        "PROJECT_ID":       args.project_id,
        "PROJECT_ID_LOWER": args.project_id.lower(),
        "PROJECT_NAME":     args.name,
        "ADDRESS":          args.address,
        "STATE":            args.state,
        "LGA":              args.lga,
        "LAND_AREA":        args.land_area,
        "CURRENT_USE":      args.current_use,
        "ZONING":           args.zoning,
        "PROPOSED_USE":     args.proposed_use,
        "DATE":             date_str,
    }

    project_dir = SDARPP_OPS_ROOT / "projects" / args.project_id
    wiki_dir    = project_dir / "wiki"

    print(f"\n🚀 Creating project: {args.project_id}")
    print(f"   Location: {args.address}")
    print(f"   LGA: {args.lga}, {args.state}\n")

    # ── Write project files ──────────────────────────────────
    write_file(project_dir / "README.md",           readme(ctx))
    write_file(wiki_dir / "index.md",               wiki_index(ctx))
    write_file(wiki_dir / "project_state.md",       project_state(ctx))
    write_file(wiki_dir / "decisions.md",           decisions_register(ctx))
    write_file(wiki_dir / "risks.md",               risk_register(ctx))
    write_file(wiki_dir / "budget.md",              budget_template(ctx))
    write_file(wiki_dir / "schedule.md",            schedule_template(ctx))
    write_file(wiki_dir / "stakeholder_list.md",    stakeholder_list(ctx))
    write_file(project_dir / ".gitkeep",            "")

    # ── Write agent job starters ─────────────────────────────
    jobs_dir = project_dir / "agent-jobs"
    write_file(jobs_dir / "01_diba_briefing.md",    diba_issue_body(ctx))
    write_file(jobs_dir / "02_site_investigation.md", agent_job_site_investigation(ctx))

    # ── Output JSON for next steps ───────────────────────────
    output = {
        "status": "created",
        "project_id": args.project_id,
        "project_dir": str(project_dir),
        "wiki_dir": str(wiki_dir),
        "next_steps": [
            "1. git add + commit + push this project",
            "2. Create DIBA issue from agent-jobs/01_diba_briefing.md",
            "3. DIBA agent generates intelligence briefing",
            "4. Site Investigator runs after DIBA",
            "5. Design PoC agent generates 4 scenarios",
        ]
    }

    print(f"\n✅ Project {args.project_id} created successfully!")
    print(f"\n📋 Next Steps:")
    for s in output["next_steps"]:
        print(f"   {s}")

    print(f"\n📂 Files created in:")
    print(f"   {project_dir}")

    return output


if __name__ == "__main__":
    main()
